## R Packages

`r str_extract(r_citations$pkgs, "We.*")`

## Multilevel Models

### Observed Certainty

A multilevel model using truth judgment and repetition status as predictors for certainty rating across all datasets and including random intercepts for subjects and datasets revealed significant effects of repetition $b =$ `r summary(cert_model_dichotomous)$coefficients[2, 1] %>% apa_num()`, $SE =$ `r summary(cert_model_dichotomous)$coefficients[2, 2] %>% apa_num()`, `r paste0("t(", summary(cert_model_dichotomous)$coefficients[2, 3] %>% apa_num(), ") = ", summary(likert_model_certainty_by_repetition)$coefficients[2, 4] %>% apa_num())`, $p$ `r summary(cert_model_dichotomous)$coefficients[2, 5] %>% apa_p()`, truth judgment $b =$ `r summary(cert_model_dichotomous)$coefficients[3, 1] %>% apa_num()`, $SE =$ `r summary(cert_model_dichotomous)$coefficients[3, 2] %>% apa_num()`, `r paste0("t(", summary(cert_model_dichotomous)$coefficients[3, 3] %>% apa_num(), ") = ", summary(likert_model_certainty_by_repetition)$coefficients[3, 4] %>% apa_num())`, $p$ `r summary(cert_model_dichotomous)$coefficients[3, 5] %>% apa_p()`, and their interaction $b =$ `r summary(cert_model_dichotomous)$coefficients[4, 1] %>% apa_num()`, $SE =$ `r summary(cert_model_dichotomous)$coefficients[4, 2] %>% apa_num()`, `r paste0("t(", summary(cert_model_dichotomous)$coefficients[4, 3] %>% apa_num(), ") = ", summary(likert_model_certainty_by_repetition)$coefficients[4, 4] %>% apa_num())`, $p$ `r summary(cert_model_dichotomous)$coefficients[4, 5] %>% apa_p()`. Certainty is increased for "true" judgments, repeated statements, and especially for "true" judgments of repeated statements.

### Artificial Certainty

A multilevel model using truth judgment and repetition status as predictors for artificial certainty rating across all datasets including random intercepts for subjects and datasets revealed significant effects of repetition $b =$ `r summary(likert_model_certainty_by_repetition)$coefficients[2, 1] %>% apa_num()`, $SE =$ `r summary(likert_model_certainty_by_repetition)$coefficients[2, 2] %>% apa_num()`, 
`r paste0("t(", summary(likert_model_certainty_by_repetition)$coefficients[2, 3] %>% apa_num(), ") = ", summary(likert_model_certainty_by_repetition)$coefficients[2, 4] %>% apa_num())`, $p$ `r summary(likert_model_certainty_by_repetition)$coefficients[2, 5] %>% apa_p()`, truth judgment $b =$ `r summary(likert_model_certainty_by_repetition)$coefficients[3, 1] %>% apa_num()`, $SE =$ `r summary(likert_model_certainty_by_repetition)$coefficients[3, 2] %>% apa_num()`, `r paste0("t(", summary(likert_model_certainty_by_repetition)$coefficients[3, 3] %>% apa_num(), ") = ", summary(likert_model_certainty_by_repetition)$coefficients[3, 4] %>% apa_num())`, $p$ `r summary(likert_model_certainty_by_repetition)$coefficients[3, 5] %>% apa_p()`, and their interaction $b =$ `r summary(likert_model_certainty_by_repetition)$coefficients[4, 1] %>% apa_num()`, $SE =$ `r summary(likert_model_certainty_by_repetition)$coefficients[4, 2] %>% apa_num()`, `r paste0("t(", summary(likert_model_certainty_by_repetition)$coefficients[4, 3] %>% apa_num(), ") = ", summary(likert_model_certainty_by_repetition)$coefficients[4, 4] %>% apa_num())`, $p$ `r summary(likert_model_certainty_by_repetition)$coefficients[4, 5] %>% apa_p()`. Artificial certainty is significantly higher for repeated statements, lower for "true" judgments than "false" judgments of new statements, but higher for "true" judgments than "false" judgments of repeated statements.


## Included data

(ref:table-effsize-overview) Overview of data included

```{r table-effsize-overview}
overview_table_data_clean <- overview_table_data %>% 
  ungroup() %>% 
  mutate(
    first_author = sub(" ", "", (sub(",.*", "", authors))),
    publication = paste0("@", first_author, conducted)
  ) %>% 
  select(
    publication,
    procedure_id,
    n_participants,
    n_statements,
    truth_rating_scale,
    d_control,
    d_art,
    rel_control,
    rel_art
  ) %>% 
  mutate(
    procedure_id = as.character(round(procedure_id, 0)),
    n_participants = as.character(round(n_participants, 0)),
    n_statements = as.character(round(n_statements, 0)),
    # publication = paste0(authors, " (", conducted, ")")
  ) %>% 
  # select(-authors, -conducted) %>% 
  select(publication, everything())

apa_table(overview_table_data_clean,
          caption = "Overview of data included in the analysis Note. The table summarizes key characteristics and results for each procedure, including publication, procedure ID, number of participants (n_participants), and number of statements (n_statements). truth_rating_scale indicates the response format used in the original data (dichotomous vs. likert vs. range). d_control and d_art denote effect size estimates (Cohen’s d for repeated measures) for the original (control) and counterfactual (artificially transformed) data, respectively. rel_control and rel_art represent the corresponding reliability estimates (average Spearman–Brown corrected split-half correlations).")
```