---
title             : "Beyond True and False: Graded Truth Ratings Conflate Perceived Truth and Certainty"
shorttitle        : "Graded Truth Ratings Conflate Perceived Truth and Certainty"

author: 
  - name          : "Sven Lesche"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Hauptstraße 47-51, 69117 Heidelberg"
    email         : "sven.lesche@psychologie.uni-heidelberg.de"
    # role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
    #   - "Conceptualization"
    #   - "Writing - Original Draft Preparation"
    #   - "Writing - Review & Editing"
  - name          : "Annika Stump"
    affiliation   : "2"
    # role:
    #   - "Conceptualization"
    #   - "Writing - Original Draft Preparation"
    #   - "Writing - Review & Editing"
affiliation:
  - id            : "1"
    institution   : "Ruprecht-Karls-University Heidelberg"
  - id            : "2"
    institution   : "Albert-Ludwigs-University Freiburg"
  # add a second id using this syntax

authornote: |
  The authors contributed equally to this work. All code needed to replicate the analyses and reproduce the manuscript can be found here: PLACEHOLDER.

abstract: |
  Truth judgments are commonly assessed using graded rating scales, which are often assumed to provide a more precise measure of perceived truth than dichotomous truth judgments. However, graded truth ratings may capture not only perceived truth but also certainty in that judgment. Using data from the Truth Effect Database (TED), comprising 45 studies, 8,807 participants, and 621,112 trials on the illusory truth effect (ITE), we investigated the psychological meaning and psychometric consequences of different truth-judgment response formats.
   First, we examined whether repetition influences certainty independently of perceived truth. Across datasets containing separate certainty ratings, repetition increased certainty for statements judged as both true and false. A comparable pattern emerged in graded truth ratings, where repetition moved responses farther away from the scale midpoint regardless of judgment direction. These findings suggest that graded truth ratings reflect both perceived truth and certainty. Second, we compared dichotomous and graded response formats with respect to effect size and reliability. Response format had little impact on the effect size of the ITE. In contrast, reliability was affected by response format: transforming dichotomous judgments into graded responses using accompanying certainty ratings increased reliability, whereas dichotomizing graded ratings reduced reliability.
   Together, these findings challenge the assumption that graded truth ratings merely provide a more precise measure of perceived truth. Instead, they appear to reflect a combination of perceived truth and certainty, with important implications for the interpretation of truth judgments and their psychometric properties.
  
keywords          : "truth judgments; certainty; confidence; illusory truth effect; response formats; psychometrics"
# wordcount         : "X"

bibliography      : ["r-references.bib", "truth_effect.bib"] # put your ref files here

floatsintext      : yes # for pics in text
linenumbers       : no
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no
link-citations    : true # custom addin, makes citations link to reference section
# figsintext        : yes # custom addin

classoption       : "man"
# the settings below allow compilation of APA7 style citations/documents
header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother
  - | 
    \raggedbottom
  - |
    \usepackage{hhline}
  - |
    \setlength{\parskip}{0pt}

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
output            : papaja::apa6_pdf
---
```{r setup, include = FALSE}
# Working directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# disallow tables breaking over pages
knitr::opts_chunk$set(ft.keepnext = TRUE,
                      ft.align = "left",
                      ft.latex.float = "float")
# Seed for random number generation
set.seed(1234)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed) # this adds random seed to all chunks
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

knitr::dep_auto()
```

<!-- Setup -->
```{r child = "markdown/setup.Rmd"}
```
<!-- Here we incorporate child markdown-documents as the separate parts -->

<!-- Introduction -->
```{r child = "markdown/introduction.Rmd"}
```

<!-- Method -->
```{r child = "markdown/method.Rmd"}
```

<!-- Results -->
```{r child = "markdown/results.Rmd"}
```

<!-- Discussion -->
```{r child = "markdown/discussion.Rmd"}
```

<!-- References -->
\newpage
# References
::: {#refs custom-style="Bibliography"}
:::

\newpage

# (APPENDIX) Appendix {-}

```{r child = "markdown/appendix.Rmd"}
```


